version: '1'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - WEBHOOK_URL=https://xxxx-xxx-xx-xx-xxx.ngrok-free.app/
    command: start
    restart: unless-stopped

volumes:
  n8n_data:
    external: true
